services:
  - type: web
    name: tin-chi-carbon-backend
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
